### ISSUE TITLE
Add All Contributors bot back-end

### ISSUE THREAD

**Issue by fricoben** [starknet-id/quest_server#278]
## Description

We want to recognize all contributors to this project using the All Contributors bot. This will automate the process of adding contributors to our README.md file.

## Tasks
- [x] 1. Add the All Contributors bot to the repository
- [ ] 2. Set up the initial configuration
- [ ] 3. Update the README.md file with the contributors section
- [ ] 4. Document the process for contributors to add themselves

## Implementation Details

1. Create a `.all-contributorsrc` file in the root of the repository with the following content:

```json
{
  "files": ["README.md"],
  "imageSize": 100,
  "commit": false,
  "contributors": [],
  "contributorsPerLine": 7,
  "projectName": "Starknet Quest",
  "projectOwner": "lfglabs-dev",
  "repoType": "github",
  "repoHost": "https://github.com",
  "skipCi": true,
  "commitConvention": "none"
}
```
2. Add the following section to your README.md file:

```md
Contributors ✨
Thanks goes to these wonderful people 1:
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
This project follows the all-contributors specification. Contributions of any kind welcome!
```
3. Add instructions for contributors in the README.md file:

```md
## Adding yourself as a contributor

If you've contributed to this project, you can easily add yourself to the contributors list by commenting on any issue or pull request with: `@all-contributors please add <your-github-username> for <contribution-type>`

For example: `@all-contributors please add @fricoben for code, business, and ideas`
 
For a full list of contribution types, check out the [emoji key](https://allcontributors.org/docs/en/emoji-key).
```

After implementing these changes, the All Contributors bot will be set up and ready to use in our repository you can test to add yourself as a contributor

**Comment by ooochoche** [comment]
@fricoben I can work on this issue if it is still open for contributions.

**Comment by Benjtalkshow** [comment]
@fricoben 
Can i work on this?

**Comment by fricoben** [comment]
this was done

**Comment by fricoben** [comment]
Actually no it wasn't done so I'll add it to the OD hack

**Comment by fricoben** [comment]
Actually no it wasn't done so I'll add it to the OD hack

**Comment by ooochoche** [comment]
@fricoben can I take on this?

**Comment by PoulavBhowmick03** [comment]
I'm Poulav Bhowmick, a Starknet Wolf and a contributor to the Starknet ecosystem, and have contributed to the starknet quest repositories too

## Approach

I will add the all contributors bot to the repo and setting up the initial configuration in the .all-contributorsrc file. Next, I will update the README.md to include a dedicated "Contributors" section, which will automatically populate with contributor information. Additionally, I will document the process for contributors to easily add themselves, ensuring that everyone who has contributed to the project can be recognized.
### ETA - 2-3 hours

Thanks!

**Comment by SoarinSkySagar** [comment]
I would like to work on this.

### ETA: 1 Hour

**Comment by Gerson2102** [comment]
Hey can I work on this one? I'm applying because I'm done with my current issue.

**Comment by MPSxDev** [comment]
Hello @fricoben, I would love to work on this issue in this great project
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.
